<?php
/***************************************************************************/
/*
/* 	----------------------------------------------------------------------
/* 								DO NOT EDIT THIS FILE
/*	----------------------------------------------------------------------
/* 
/*				Huge thanks to @devinsays for the Theme Options Framework 
/*				(https://github.com/devinsays/options-framework-plugin)
/*										
/*									@since 1.6
/*									@alter 2.1.3
/***************************************************************************/

$functions_path = TEMPLATEPATH . '/functions/';
$widgets_path = TEMPLATEPATH . '/functions/widgets/';

// Set error reporting
error_reporting(E_ERROR);

/*-----------------------------------------------------------------------------------
 			Add default options and show Options Panel after activate  
-----------------------------------------------------------------------------------*/
if (is_admin() && isset($_GET['activated'] ) && $pagenow == "themes.php" ) {
	//Do redirect
	header( 'Location: '.admin_url().'themes.php?page=options-framework' ) ;
}

// --------------  Custom Widgets  -------------- 
include($widgets_path . 'flickr.php');
include($widgets_path . 'twitter.php');
include($widgets_path . 'category-posts.php');
include($widgets_path . 'testimonials.php');
include($widgets_path . 'related-posts.php');
include($widgets_path . 'popular-posts.php');
include($widgets_path . 'share.php');
include($widgets_path . 'ads.php');

// --------------  Custom Post Fields -------------- 
if( current_user_can( 'edit_posts' ) && is_admin()){
	include($functions_path . 'admin-custom.php');
}

// --------------  Custom Excerpt Lengths -------------- 
include($functions_path . 'custom-excerpts.php');	

// --------------  Theme Update -------------- 
if( is_admin() ){
    require($functions_path . '/theme-updates.php');
}

// --------------  Other custom functions -------------- 
require($functions_path . 'shaken-utils.php');
require($functions_path . 'custom-styles.php');

// --------------  Options Framework -------------- 
if(is_admin()){
    require_once ($functions_path . '/admin-options/options-framework.php');
}

if ( ! function_exists( 'of_get_option' ) ) {
	/**
	 * Get Option.
	 *
	 * Helper function to return the theme option value.
	 * If no value has been saved, it returns $default.
	 * Needed because options are saved as serialized strings.
	 */
	 
	function of_get_option( $name, $default = false ) {
		$config = get_option( 'optionsframework' );

		if ( ! isset( $config['id'] ) ) {
			return $default;
		}

		$options = get_option( $config['id'] );

		if ( isset( $options[$name] ) ) {
			return $options[$name];
		}

		return $default;
	}
}

?>